version: '3.9'
services:
  elixir:
    build:
      context: .
    # environment:
    #   - MIX_ENV
    # volumes:
    #   - ./src:/app
    ports:
      - '4000:4000'
    depends_on:
      - db
  db:
    image: 'postgres:13.1-alpine'
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
